name: first workflow
on: [push]

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: echo a string
              run: echo "Github Actions Welcome Welcome"
            
            - name: Multiline Command
              run: |
                echo "Hi"
                echo "I am not good "
            - run: echo "Test without run"






