name: streamlit run
on: [push]

jobs:
  my_streamlit_run:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Requirements
        uses: py-actions/py-dependency-install@v4.1.0

      - name: Run Python File
        run: python3 main.py
